#!/bin/sh
#
#  package_project
#
#  Package project & documentaton for distribution
#
#  Steps: 
#  1) Run make in ip_repo/sde_trigger/hdl/
#  2) Do Vivado Synthesis, implementation and create bitmap for project
#  3) Run this script from the uub-firmware base
#  4) Commit & push to GitHub; don't forget to push the tag (push --tags) 
#     created by this script.
#
#  14-Aug-2016 DFN Original version
#  01-Sep-2016 DFN Modified to work with GitHub
#  18-Sep-2016 DFN Add xparameters.h and uub_proto2_wrapper.hdf
#  10-Oct-2018 DFN Add xparameters_ps.h
#  22-Feb-2019 DFN Add rd_interface and test_control header files & driver code
#  06-May-2019 DFN Clean up steps for pushing .tgz file to GitHub
#  13-Apr-2020 DFN Add uboot.bin, system.dtb to package

VERSION="`cat  ip_repo/sde_trigger/hdl/sde_trigger_id`"

# Clean up any files left in temp directory
rm -rf temp
mkdir temp

# Copy new set of files to temp directory
cp docs/SDE_PLD_Firmware_Specs.pdf temp/SDE_PLD_Firmware_Specs_${VERSION}.pdf

cp ip_repo/sde_trigger/drivers/sde_trigger/src/*.h temp/
cp ip_repo/sde_trigger/drivers/sde_trigger/src/sde_trigger.c temp/
cp ip_repo/time_tagging_1.0/drivers/time_tagging_v1_0/src/*.h temp/
cp ip_repo/time_tagging_1.0/drivers/time_tagging_v1_0/src/time_tagging.c temp/
cp ip_repo/rd_interface_2.0/drivers/rd_interface_v2_0/src/*.h temp/
cp ip_repo/rd_interface_2.0/drivers/rd_interface_v2_0/src/rd_interface.c temp/
cp ip_repo/test_control_1.0/drivers/test_control_v1_0/src/*.h temp/
cp ip_repo/test_control_1.0/drivers/test_control_v1_0/src/test_control.c temp/
cp ip_repo/digital_interface_1.0/drivers/digital_interface_v1_0/src/*.h temp/
cp ip_repo/digital_interface_1.0/drivers/digital_interface_v1_0/src/digital_interface.c temp/

WD=`pwd`

cd wp2/uub_v3
find ./ -name xparameters.h -exec cp {} ../../temp/ \;
find ./ -name xparameters_ps.h -exec cp {} ../../temp/ \;
find ./ -name uub_v3_wrapper.hdf -exec cp {} ../../temp/ \;
find ./uub_v3.sdk -name uboot.bin -exec cp {} ../../temp/ \;
cd $WD

cp wp2/device_tree/auger_customized/system.dtb temp/
#cp wp2/uub_v3/src/test_periph/src/*.c temp/
#cp wp2/uub_v3/src/test_periph/src/*.h temp/
#cp wp2/uub_v3/src/test_periph/src/README temp/README_${VERSION}
cp wp2/uub_v3/uub_v3.runs/impl_1/uub_v3_wrapper.bit temp/fpga.bit

# Package everything up into a tar file
#(cd wp5; rm *.tgz)
(cd temp; tar czf ../wp5/uub_firmware_${VERSION}.tgz ./*)
git add wp5/uub_firmware_${VERSION}.tgz

# Tag this version
git tag ${VERSION}

echo "If all goes well, don't forget to do:"
echo "  1) git status"
echo "  2) git commit -a"
echo "  3) git push origin master"
echo "  4) git push --tags"

